version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies needed."

  build:
    commands:
      - echo "Build started on `date`"

  post_build:
    commands:
      - echo "Deploying to S3..."
      # This command syncs your files directly to the root of the bucket
      - aws s3 sync . s3://dn-exp-9-devops --delete